### ISSUE TITLE
Error with player.getTargetBlock

### ISSUE THREAD

**Issue by keough99** [Dabblecraft2DevTeam/NavyCraft#2]
![unknown](https://user-images.githubusercontent.com/13394623/34588660-27211e74-f17c-11e7-8b24-b6290320f382.png)
![unknown 1](https://user-images.githubusercontent.com/13394623/34588666-327a39ea-f17c-11e7-9e73-1657b8c57e0f.png)
those are the current issues needs to be fixed before anything else.

**Comment by keough99** [comment]
partially fixed in most recent commit but needs more fixes

**Comment by Solmex72** [comment]
![screenshot 3](https://user-images.githubusercontent.com/21145269/34908861-07a6a998-f865-11e7-8838-f1e2a6e5a0fb.png)

**Comment by Solmex72** [comment]
Don't know how that could help, Check out my version if you need a reference
http://github.com/Solmex72/NavyCraft

**Comment by keough99** [comment]
Issue Fixed In Latest Version
