### ISSUE TITLE
Plugin doesn't work. At all.

### ISSUE THREAD

**Issue by Terra1** [Dabblecraft2DevTeam/NavyCraft#7]
What Minecraft version are you using (include the server type. Example: Spigot, Sponge):
1.12.2, Spigot.
What Verion of the plugin are you using:
3.0.1
Put your server log into [Pastebin](https://pastebin.com/) and paste the link:
https://pastebin.com/F7Gkuv39
Details of your issue:
The plugin doesn't work. At all. It straight up doesn't load.

**Comment by keough99** [comment]
@Terra1 I found your issue.
`org.bukkit.plugin.UnknownDependencyException: Vault`
Vault is required for the plugin to work. Installing vault will fix the issue

**Comment by Terra1** [comment]
Still doesn't work.
https://pastebin.com/HUtrhzWF
Here's some more logs.

**Comment by keough99** [comment]
@Terra1 try the latest release which is V3.0.1.1
https://github.com/Dabblecraft2DevTeam/NavyCraft/releases/tag/v3.0.1.1
this may fix the issue
