### ISSUE TITLE
Plugin thinks everything is safedock.

### ISSUE THREAD

**Issue by Terra1** [Dabblecraft2DevTeam/NavyCraft#8]
What Minecraft version are you using (include the server type. Example: Spigot, Sponge):
1.2.2
What Verion of the plugin are you using:
3.0.1.1
Put your server log into [Pastebin](https://pastebin.com/) and paste the link:
https://pastebin.com/n5gJw7Lr
Details of your issue:
Basically, NavyCraft thinks the entire map is safedock, and screams at you when you try to load cannons or fire AA guns.
![2018-10-27_10 14 54](https://user-images.githubusercontent.com/17017931/47601477-848c9c80-d9d1-11e8-8c84-651e55ebd99b.png)

**Comment by keough99** [comment]
In order for the plugin to work you need to enable the world in the
navycraft config otherwise the plugin will say everything is safedock. I
also recommend making a world guard region named safedock

**Comment by keough99** [comment]
In the config.yml there's this config value:
```
#Defines which worlds the plugin's weapons will funciton in.
EnabledWorlds: WarWorld,BattleWorld,TankSpawn
```

**Comment by Terra1** [comment]
Thank you, it's fixed.
